### PR TITLE
updated my bio and picture

### PR DESCRIPTION
**Pull request by j-hanania**
updated bio and picture in subspace page

### CODE REVIEW

**Comment by j-hanania** [comment]
Hi Rogers, apologies, my first edit was to erase the URL in the local config file as was suggested to try to bypass my port issue but that didn’t work. Then I updated the subspace yml with my bio and added my picture, and used “bundle exec jekyll serve —config _config_local.yml —port 4001”. That worked to create a local website that I looked correct, and that’s what was committed. It must have rewritten aspects of the HTML file as a result, including changing all values of 4000 to 4001 and swap Hussain and Mite’s bios (as far as I can see it’s a swap and no info is lost). Let me know if any of that was wrong to do, again my apologies

**Comment by esalman** [comment]
@j-hanania  no worries at all! Just make a new pull request where only `data/subspace_volunteers.yml` has been modified. Can you do that?

**Comment by esalman** [comment]
Yes, the _site folder is in gitignore and should not have been merged. But no big deal.. it can be fixed later. 

@j-hanania should submit a PR that contains modifications to the yml file only. The html file is going to stay in his local when he compiles the site.. but as long as it is not being committed that is fine.

**Comment by rsilva8** [comment]
@esalman The HTML file is already being tracked since before @j-hanania first pulled. The only way he can send a PR without the HTML file is if he removes it from the git index, which I think is the right thing to do bc it should have never been there.

The problem is that it will cause the HTML file to be deleted locally the first time anyone pulls the repo after this git index update. This would be OK IF `jekyll` creates the file again automatically. Is that the case @esalman ?

**Comment by esalman** [comment]
Yes correct, doesn't matter if the html file is delete from the index, it will be regenerated every time the site is compiled.

**Comment by rsilva8** [comment]
@j-hanania Could you try the following in your develop branch? (check if the path&filename are correct)

1. If you made any changes recently: stage and commit the changed files in your develop branch.
2. Then,

`git rm --cached  _site/study-groups/multivariate-blind-subspace.html`
`git commit -m "Removed HTML file."`

3. Continue from step 5 e) in the guide from Carlos.

4. You may not need to repeat step 6... check if you can just 'update' this PR.
Otherwise, use step 6 in the guide to create a new PR.

**Comment by j-hanania** [comment]
Looking into it now! 

I tried to commit just the yml and jpg files yesterday but it got blocked saying that my branch wasn't up to date, despite following Carlos' workflow instructions. I'll try now again and see if it works.

**Comment by rsilva8** [comment]
@j-hanania
It looks like some conflicts popped up in your develop branch after we accepted Anjali's PR.
This is normal. It only means they are gonna have to be resolved before updating your PR.
FYI, that can be a bit frustrating, but we will help you along the way. :-)
Just keep us posted of any problems you come across.

Heads up: at this point you should go from step 5 d) in Carlos's guide to update your local master and rebase you local develop branch. If the commit is being blocked, you may have to `git add` first. Otherwise, send us the commands you issued and the full output you see on the terminal.

Thanks for your patience!

**Pull request merged**
