### PR TITLE
Update bio and profile picture (Anjali)

### PR DESCRIPTION
**Pull request by anjaliagarwal8**
modified:   _data/subspace_volunteers.yml
	modified:   _site/study-groups/multivariate-blind-subspace.html
	img/people/anjali.jpg

### CODE REVIEW

**Comment by rsilva8** [comment]
Thanks, @anjaliagarwal8 .

Couple of notes:
1. the [_config.yml](https://github.com/brainspaceinitiative/brainspaceinitiative.github.io/pull/15/files#diff-ecec67b0e1d7e17a83587c6d27b6baaaa133f42482b07bd3685c77f34b62d883) file should Not be modified.
Instead, use the local config file:
`bundle exec jekyll serve --livereload --config _config_local.yml`
You can drop `--livereload` if you get some error.
Please, undo your changes to _config.yml and modify only _config_local.yml, if needed

2. You should Not commit changes to [_site/study-groups/multivariate-blind-subspace.html](https://github.com/brainspaceinitiative/brainspaceinitiative.github.io/pull/15/files#diff-5b75180ae58d64855420aebf83c8539318f9317c3cd99a03d59f0ff7144dd87d) 
You should remove it from the git index as follows:

> 1. If you made any changes recently: stage and commit the changed files in your develop branch.
> 2. Then,
> `git rm --cached _site/study-groups/multivariate-blind-subspace.html`
> `git commit -m "Removed HTML file."`
> 
> Continue from step 5 e) in the guide from Carlos.
> 
> You may not need to repeat step 6... check if you can just 'update' this PR.
> Otherwise, use step 6 in the guide to create a new PR.

**Comment by anjaliagarwal8** [comment]
Hi @rsilva8 , Thanks.
I have implemented the points you mentioned and committed the final changes.

**Comment by esalman** [comment]
I merged it but then noticed the picture is missing. Probably needs another update to the commit.

**Comment by rsilva8** [comment]
thank you, @anjaliagarwal8 !

Please, send another PR to include your picture too. It was not included somehow.

**Pull request merged**
